language: java
# use Java 8
jdk:
- openjdk8

sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2

# Build Maven project
script:
    - cd EmailsToTelegramService && mvn clean install -DskipTests=true && cd ..
    - cd TrashEmailService && mvn clean install -DskipTests=true
